import https from "https";
import { CommandContext } from "./types";

function fetchText(url: string, opts: { timeout?: number } = {}): Promise<string> {
  return new Promise((resolve, reject) => {
    const req = https.get(url, { headers: { "User-Agent": "NX-MD-Bot/1.0" } }, (res) => {
      let data = "";
      res.on("data", (c: any) => { data += c; });
      res.on("end", () => resolve(data));
    });
    req.on("error", reject);
    req.setTimeout(opts.timeout || 12000, () => { req.destroy(); reject(new Error("timeout")); });
  });
}

async function callFreeAI(prompt: string): Promise<string> {
  const url = `https://text.pollinations.ai/${encodeURIComponent(prompt)}`;
  const text = await fetchText(url, { timeout: 15000 });
  return text.trim() || "Sorry, I couldn't generate a response right now.";
}

async function aiCommand(ctx: CommandContext, label: string, systemPrompt: string) {
  const { sock, replyTo, args, prefix, command } = ctx;
  if (!args.trim()) {
    await sock.sendMessage(replyTo, {
      text: `🤖 *${label}*\n\nUsage: *${prefix}${command} <prompt>*\nExample: *${prefix}${command} ${systemPrompt.slice(0, 50)}...*`,
    });
    return;
  }
  await sock.sendMessage(replyTo, { text: "🤔 _Processing..._" });
  try {
    const fullPrompt = `${systemPrompt}\n\nUser: ${args.trim()}\nAssistant:`;
    const response = await callFreeAI(fullPrompt);
    await sock.sendMessage(replyTo, {
      text: `🤖 *${label}*\n\n${response}\n\n_Powered by NX-MD AI_`,
    });
  } catch {
    await sock.sendMessage(replyTo, {
      text: `❌ AI service temporarily unavailable. Try again later.`,
    });
  }
}

export async function cmd_gpt(ctx: CommandContext) {
  await aiCommand(ctx, "GPT AI", "You are a helpful, knowledgeable AI assistant. Answer questions clearly and concisely.");
}

export async function cmd_gemini(ctx: CommandContext) {
  await aiCommand(ctx, "Gemini AI", "You are a helpful AI assistant like Google Gemini. Provide clear and accurate responses.");
}

export async function cmd_blackbox(ctx: CommandContext) {
  await aiCommand(ctx, "BlackBox AI", "You are BlackBox AI. Answer programming and technical questions with detailed explanations and code examples.");
}

export async function cmd_deepseek(ctx: CommandContext) {
  await aiCommand(ctx, "DeepSeek AI", "You are DeepSeek AI. Provide deep, insightful analytical responses with reasoning.");
}

export async function cmd_code(ctx: CommandContext) {
  const { sock, replyTo, args, prefix, command } = ctx;
  if (!args.trim()) {
    await sock.sendMessage(replyTo, {
      text: `💻 *Code Generator*\n\nUsage: *${prefix}${command} <description>*\nExample: *${prefix}code create a function to sort an array in JavaScript*`,
    });
    return;
  }
  await sock.sendMessage(replyTo, { text: "💻 _Generating code..._" });
  try {
    const prompt = `You are an expert programmer. Write clean, well-commented code for this request. Always format code in code blocks.\n\nRequest: ${args.trim()}\n\nProvide the code with brief explanation:`;
    const response = await callFreeAI(prompt);
    await sock.sendMessage(replyTo, {
      text: `💻 *Code Generator*\n\n${response}\n\n_Generated by NX-MD AI_`,
    });
  } catch {
    await sock.sendMessage(replyTo, { text: `❌ Code generation failed. Try again.` });
  }
}

export async function cmd_programming(ctx: CommandContext) {
  await cmd_code(ctx);
}

export async function cmd_analyze(ctx: CommandContext) {
  await aiCommand(ctx, "AI Analyzer", "You are an expert analyst. Analyze the given topic, text, or data and provide insights, patterns, and recommendations.");
}

export async function cmd_summarize(ctx: CommandContext) {
  await aiCommand(ctx, "AI Summarizer", "You are a summarization expert. Create a concise, comprehensive summary of the provided text or topic.");
}

export async function cmd_translate2(ctx: CommandContext) {
  const { sock, replyTo, args, prefix, command } = ctx;
  if (!args.trim()) {
    await sock.sendMessage(replyTo, {
      text: `🌍 *AI Translate*\n\nUsage: *${prefix}${command} <language>: <text>*\nExample: *${prefix}translate2 Spanish: Hello, how are you?*`,
    });
    return;
  }
  const colonIndex = args.indexOf(":");
  if (colonIndex === -1) {
    await sock.sendMessage(replyTo, {
      text: `Usage: *${prefix}translate2 <language>: <text>*\nExample: *${prefix}translate2 French: Good morning*`,
    });
    return;
  }
  const lang = args.slice(0, colonIndex).trim();
  const text = args.slice(colonIndex + 1).trim();
  await sock.sendMessage(replyTo, { text: "🌍 _Translating..._" });
  try {
    const prompt = `Translate the following text to ${lang}. Only output the translation, nothing else:\n\n"${text}"`;
    const response = await callFreeAI(prompt);
    await sock.sendMessage(replyTo, {
      text: `🌍 *Translation to ${lang}*\n\n📥 Original: ${text}\n📤 Translated: ${response}`,
    });
  } catch {
    await sock.sendMessage(replyTo, { text: `❌ Translation failed. Try again.` });
  }
}

export async function cmd_translate(ctx: CommandContext) {
  await cmd_translate2(ctx);
}

export async function cmd_recipe(ctx: CommandContext) {
  await aiCommand(ctx, "Recipe Creator", "You are a professional chef. Create a detailed recipe with ingredients, steps, cooking time, and serving size. Format it clearly.");
}

export async function cmd_story(ctx: CommandContext) {
  await aiCommand(ctx, "Story Generator", "You are a creative story writer. Write an engaging short story based on the prompt. Make it interesting with characters and plot.");
}

export async function cmd_teach(ctx: CommandContext) {
  await aiCommand(ctx, "AI Teacher", "You are an expert teacher. Explain the topic clearly and engagingly, using examples and analogies where helpful. Make it easy to understand.");
}

export async function cmd_generate(ctx: CommandContext) {
  await aiCommand(ctx, "AI Generator", "You are a creative AI. Generate content based on the prompt provided. Be creative and thorough.");
}

export async function cmd_doppleai(ctx: CommandContext) {
  await aiCommand(ctx, "DoppleAI", "You are DoppleAI, an advanced conversational AI. Engage naturally and helpfully with the user.");
}

export async function cmd_dalle(ctx: CommandContext) {
  const { sock, replyTo, args, prefix, command } = ctx;
  if (!args.trim()) {
    await sock.sendMessage(replyTo, {
      text: `🎨 *DALL-E Image Generation*\n\nUsage: *${prefix}${command} <description>*\nExample: *${prefix}dalle a sunset over Nairobi skyline*\n\n⚠️ Image generation requires premium API key.\nContact: 0758891491`,
    });
    return;
  }
  await sock.sendMessage(replyTo, {
    text: `🎨 *Image Generation*\n\n📝 Prompt: ${args.trim()}\n\n⚠️ DALL-E requires OpenAI API key configuration.\nContact Nutterx Technologies: 0758891491\n🔗 https://wa.me/254758891491`,
  });
}
